### ISSUE TITLE
Error handling for get_bearer_token in Qualys connector  

### ISSUE THREAD

**Issue by omkar-g** [IBM/cp4s-car-connectors#52]
There is no error handing in get_bearer_token function here: https://github.com/IBM/cp4s-car-connectors/blob/develop/connectors/qualys/connector/server_access.py#L132

This leads failure in `get_applications` function without proper error message.

**Comment by thangaraj-ramesh** [comment]
The mentioned issue is addressed : PR # : https://github.com/IBM/cp4s-car-connectors/pull/56
 Affected Files: server_access.py
