### ISSUE TITLE
`vmdrVulnList` is array if more that one element, but object if its one

### ISSUE THREAD

**Issue by omkar-g** [IBM/cp4s-car-connectors#54]
Here: https://github.com/IBM/cp4s-car-connectors/blob/653ca02a05cb7a31f940212ca4523f5b7432e618/connectors/qualys/connector/data_handler.py#L170

and other places.

`vmdrVulnList` assumed to be always an array, but it is an object when there is only one entry.

**Comment by thangaraj-ramesh** [comment]
The mentioned issue is addressed : PR # : https://github.com/IBM/cp4s-car-connectors/pull/56
Affected Files: data_handler.py ( Single vulnerabilities will be converted into list )
